name: status_code_test
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.4
  confetti: ^0.7.0
  file_picker: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  path_provider: ^2.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assests/logo5.png
    - assests/mascot-blush.png
    - assests/th.jpeg
  uses-material-design: true
